# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&3Treasures &8>> '
debug-enabled: false

# Should we hide the block for the player?
# Note: Sends a block change, so only MC client can't see the block, server will still use it and block player movement. Reappears on interaction.
hide-block: true

# Should we shoot fireworks?
fireworks: true

# Sound to play when the players opens a treasure.
sound:
  enabled: true
  type: ENTITY_CHEST_OPEN
  pitch: 1
  volume: 1

# Worlds where this plugin is enabled.
worlds:
  - 'world'

# General treasure rewards
rewards:
  commands:
    - 'tm add %player% 10'
  broadcast:
    - ''
    - '&f%player% &7found a treasure!'
    - ''