# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&3Treasures &8| '
debug-enabled: false

# Block hide settings
hide-block:
  enabled: true

  # When hiding only for the player who found it, it's through block change packets.
  # It's not permanent, any interaction set's the block right back.
  # Setting to false removes the block completely and places it back after configured time.
  only-for-player: true

  # Settings below do not apply if only-for-player is set to true, don't see a point in that.

  # Place it back?
  # This could be useful to create "who gets the most" egg hunts, with this set to false, the egg block just disappears.
  place-back: true

  # For how long to hide it?
  # In seconds.
  time: 60

# Fireworks? Picks them randomly.
fireworks: true

# Sound to play when the player opens a treasure.
sound:
  enabled: true
  type: ENTITY_CHEST_OPEN
  pitch: 1
  volume: 1

# Tool settings
tools:
  # Consume the tool item when you place a treasure?
  consume: true
  # Whether or not to drop the tool item when you delete a treasure.
  drop-on-remove: true

# Worlds where this plugin is disabled.
disabled-worlds:
  - 'world_i_dont_want_you_to_use'