# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&6Shiny Treasures &8| '
debug-enabled: false

# Policy to use on Treasures when the plugin disables/enables.
# You can actually use all of them in either disable/enable, but I don't know why you'd do that.
policy:
  # REVERT == Place the original material back
  # REMOVE == Remove all placed treasures
  disable: REMOVE
  # PLACE == Place the block configured no matter what's on the location
  # ENSURE == Place the block configured, if it's not there
  enable: PLACE

# Auto save configuration
auto-save:
  # Save interval in seconds
  interval: 300

# Block hide settings
hide-block:
  enabled: true

  # When hiding only for the player who found it, it's through block change packets.
  # It's not permanent, any interaction sets the block right back.
  # Setting to false removes the block completely and places it back after configured time.
  only-for-player: true

  # Settings below do not apply if only-for-player is set to true.

  # Place it back?
  # With this set to false, the egg block just disappears and is not placed back.
  place-back: true

  # For how long to hide it?
  # In seconds.
  time: 60

# Fireworks?
# Colors are picked randomly.
fireworks: true

# Sound to play when the player opens a treasure.
sound:
  enabled: true
  type: ENTITY_CHEST_OPEN
  pitch: 1
  volume: 1

# Tool settings
tools:
  # Consume the tool item when you place a treasure?
  consume: true

  # Whether or not to drop the tool item when you delete a treasure.
  drop-on-remove: true

  # When dropping the item, it pops up a bit. Configure the vector applied. x;y;z
  # Dynamic amounts are supported.
  pop-vector: 0.01-0.1;0.125-0.25;0.01-0.1