name: ${project.name}
main: ${project.groupId}.TreasurePlugin
version: ${project.version}
authors: [ Wertik1206 ]
commands:
  treasures:
    aliases: [ t, treasure ]
    description: Main plugin command
  treasureeditor:
    aliases: [ te ]
    description: Main plugin command
  treasuretools:
    aliases: [ tt ]
    description: Main plugin command
permissions:
  simpletreasures.open:
    default: true
    description: Permission to open treasures.
  simpletreasures.admin:
    description: Permission to manage treasures.