name: ${project.name}
main: ${project.groupId}.TreasurePlugin
version: ${project.version}
authors: [ Wertik1206 ]
commands:
  shinytreasures:
    aliases: [ st, treasure, shinytreasure, treasures ]
    description: Main plugin command
  shinytreasuretools:
    aliases: [ stt, treasuretools, tt, treasuretool, shinytreasuretool ]
    description: Main plugin command
permissions:
  shinytreasures.open:
    default: true
    description: Permission to open treasures.
  shinytreasures.admin:
    description: Permission to manage treasures.