name: ${project.name}
main: ${project.groupId}.TreasurePlugin
version: ${project.version}
authors: [ Wertik1206 ]
api-version: 1.13
softdepend: [ PlaceholderAPI, Multiverse-Core, MultiWorld ]
commands:
  shinytreasures:
    aliases: [ st, treasure, shinytreasure, treasures ]
    description: Command to manage treasures.
  shinytreasuretools:
    aliases: [ stt, treasuretools, tt, treasuretool, shinytreasuretool ]
    description: Command to manage tools.
permissions:
  treasures.open:
    default: true
    description: Permission to open treasures.
  treasures.admin:
    description: Permission to manage treasures.